### ISSUE TITLE
Allow arbitrary precision for LN(10)

### ISSUE THREAD

**Issue by AnyhowStep** [MikeMcl/decimal.js#143]
I'm working on a little arbitrary precision library as a hobby project and implemented natural log calculations. I decided to verify the results against decimal.js, since I'm pretty confident decimal.js will give the right result.

So, I tried `LN(10)` with precision 2000, and got an error that the precision was invalid.
Then, I noticed there was a hard-coded limit in the source code.

A little search revealed a related issue, https://github.com/MikeMcl/decimal.js/issues/130

I was wondering if it was possible to get a version of `LN(10)` that would actually allow arbitrary precision, with a warning that it could take a **really** long time. (for, say, 2,000 digits, or 20,000 digits)

-----

[Edit]

I guess I can compare against http://oeis.org/A002392/b002392.txt for now (first 20,000 digits)

**Comment by MikeMcl** [comment]
You can just add more digits to the `LN10` string [here](https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L29) in the *decimal.js* source file or you could use this library's sister library [decimal.js-light](https://github.com/MikeMcl/decimal.js-light) which allows the value of `LN10` to be changed at runtime.

Let me know how you get on.

**Comment by MikeMcl** [comment]
> I was wondering if it was possible to get a version of LN(10) that would actually allow arbitrary precision...

This library  *does* calculate ln(10) to arbitrary precision, but that does not mean that there is no limit, see the docs [here](http://mikemcl.github.io/decimal.js/#ln). 

The value of ln(10) is stored internally by this library to implement the `ln` function. 

This library's sister library [decimal.js-light](https://github.com/MikeMcl/decimal.js-light) allows the value of `LN10` to be changed at runtime, so that the `ln` function can calculate higher numbers of digits. 

As per your link, the value of ln(10) is widely available to thousands of digits.
