### ISSUE TITLE
0 = 1e-20

### ISSUE THREAD

**Issue by rmcdaniel** [MikeMcl/decimal.js#16]
In certain cases, adding 1 and -1 equals 1e-20 instead of 0, if the -1 is derived a certain way. If I replace the offending -1 with a new Decimal(-1) it works fine.

Please see this jsfiddle: https://jsfiddle.net/kbyeumff/

**Comment by josdejong** [comment]
You have this code:

```js
var a = new Decimal(3); // a = 3

scale = new Decimal(1).dividedBy(a); // scale = 1/3

a = a.times(scale); // a = 1

var b = new Decimal(1); // b = 1

scale = b.dividedBy(a).times(-1); // scale = -1

b = b.plus(a.times(scale)); // b = 1e-20 but should = 0 because 1 + 1 * -1 = 0

$('#result').text(b.toNumber());
```

But your assumption that `a = a.times(scale); // a = 1` is wrong: `a` is actually `0.99999999999999999999`. Try to output `console.log('a', a.toString())`

The reason is that whilst Decimal has a higher precision than regular numbers, it's still a floating point number which cannot store fractions like `1/3`, having an infinite number of digits, in a limited number of digits (20 by default in Decimal.js).
