### ISSUE TITLE
Use typescript to develop the library.

### ISSUE THREAD

**Issue by HanchaiN** [MikeMcl/decimal.js#197]
When developing the module, contributors should edit `decimal.js`, `decimal.mjs`, and probably `decimal.d.ts` and `decimal.global.d.ts`. It would be more convenient to work on a single `.ts` module and compile it to those files for users to use.

**Comment by MikeMcl** [comment]
Yes, I agree, but changes/additions to this library are likely to be minimal going forward and I have little incentive to spend time on doing that.

I will soon be releasing a more tree-shakeable version of this library - although I will probably just publish it separately as an ES module rather than Typescript module - and that is where future development is going to be focused.
