### ISSUE TITLE
I miss toFormat

### ISSUE THREAD

**Issue by vicentedealencar** [MikeMcl/decimal.js#23]
Hi, first of all thanks for this awesome library that fixes javascript math.

I tryed upgrading to 5.0, but now `toFormat is not a function` and I use it a lot. No deprecation warning or anything. The only reference I found is on 5.0 changelog: `Removed toFormat`. No further explanation :(

Why is that?

How can I format on 5.x? 

my config looks like this:

```
Decimal.config({
  format: {
    decimalSeparator: ',',
    groupSeparator: '.',
    groupSize: 3,
  }
})
```

By now I will stick with 4.0.2. 
Any pointer in the right direction would be appreciated.

**Comment by MikeMcl** [comment]
Hi. Thanks for the feedback.

I think I should put a warning at the top of the *README* that there has been some significant changes to the API.

I removed `toFormat` just because I thought that the library was getting too bloated, although looking back that seems to have been somewhat of a pointless gesture because it wasn't a lot of code anyway.

Version 5 doesn't contain any bugfixes so, yes, stick with version 4. I will continue to support it.

I think I may put `toFormat` back, but I don't want to decide that today.

**Comment by vicentedealencar** [comment]
Thanks for your response, it is good to know your position about it.

It was really easy to setup the formatting the way I needed (brazilian currency). Do you have any recommended way of formatting js numbers?

**Comment by MikeMcl** [comment]
I've published `toFormat` as an extension that can be used with both *decimal.js* and *big.js*.

https://github.com/MikeMcl/toFormat

**Comment by vicentedealencar** [comment]
Perfect! Thank you very much.

**Comment by Sevi7** [comment]
Hi @MikeMcl,

`toFormat` library is not ESM compatible. Could it be possible to put it back? I think it's so useful

Thanks!
