### ISSUE TITLE
Don't throw on invalid string

### ISSUE THREAD

**Issue by Hypercubed** [MikeMcl/decimal.js#34]
Have you considered returning something on invalid input to the constructor rather than throwing an error?  Similar to how `parseInt` and `parseFloat` returns `NaN` on invalid string.  Currently the only way to determine if a string is valid input is to catch the error:

```js
function createDecimal (value) {
  try {
    return new Decimal(value);
  } catch (e) {
    return NaN;
  }
}
```

This would allow something like:

```
const x = createDecimal(value) || createSomethingElse(value);
````

**Comment by Hypercubed** [comment]
Also, for some background I was previously using `!isNaN(value)` as a guard but `Decimal` constructor is much more liberal.  For example floating point hexadecimals.

**Comment by MikeMcl** [comment]
Previous to version 5, a Decimal with the value `'NaN'` was returned on invalid input if `Decimal.errors` was false. For version 5 I removed the `errors` configuration property, so a choice had to be made whether to throw or return NaN. I think I chose the former so that a script fails fast and it is obvious where the invalid input occurred.

**Comment by Hypercubed** [comment]
Certainly a resonable choice.  I can use `createDecimal` just as well.  Thanks.
