### ISSUE TITLE
Webpack does not play well with decimal.js 7.2.0

### ISSUE THREAD

**Issue by jsgoupil** [MikeMcl/decimal.js#49]
After this commit, https://github.com/MikeMcl/decimal.js/commit/eec7273c19fe52596d899825a22eb289b80dd098

Webpack does not play well when loading decimal.js.

I use to write 

    import * as Decimal from 'decimal.js';

And now, I get code behind a variable called `default`
![decimal error](https://cloud.githubusercontent.com/assets/808649/25507741/d2745eca-2b62-11e7-8da9-a7fba037a034.png)

Someone picked it up on @types/decimal.js
https://github.com/DefinitelyTyped/DefinitelyTyped/commit/4f2d0f8667055d145d07c9c3ad8b8c6c9bbebc4d

But with that code it still does not work. Any idea?

**Comment by R2D221** [comment]
This error is caused by the inclusion of the ES6 module (decimal.es6.js)

The quickest fix for me is to revert to version 7.1.2, but I feel like I'm missing some config option somewhere.

**Comment by dawncold** [comment]
I'm using 7.2.3 decimal.js with React, it works fine. @jsgoupil 

`import Decimal from 'decimal.js';`

**Comment by rferrerasm** [comment]
I have the same problem in an Angular application. Downgrading to 7.1.2 works.

I'm using angular-cli 1.2.2, webpack 3.3.0 and node 8.2.1.

**Comment by mjhoy** [comment]
I ran into this issue as well, v7.5.1. Is it supposed to be fixed?

**Comment by jonahbron** [comment]
I tested 7.3.0, 7.2.4, 7.2.3, 7.2.2, 7.2.1, and 7.2.0.  All of them have this same problem.  The latest version that works with Webpack for me is `7.1.2`.

https://github.com/MikeMcl/decimal.js/releases/tag/v7.1.2

**Comment by MikeMcl** [comment]
As stated above, the error is caused by the inclusion of the ES6 module, *decimal.es6.js*.

Does it work if you use `import Decimal from 'decimal.js';`?

Does it work if `"module": "decimal.es6.js",` is removed from the decimal.js *package.json*.

Does it work if you add the following to your Webpack options object:

    resolve: {
      mainFields: ["main", "module"]
    }

or

    extensions: [ '.js', '.json', '.jsx']

You just have to stop Webpack using the *decimal.es6.js* file. I may remove it if it continues to cause problems.
