### ISSUE TITLE
use of constant `1e7` is not linked to `LOG_BASE`

### ISSUE THREAD

**Issue by dimitri-xyz** [MikeMcl/decimal.js#53]
The hard constant `1e7` is used a few times in `random()` (for example [here](https://github.com/MikeMcl/decimal.js/blob/3566299686993864f1a795954f189cdfbf8e4ff9/decimal.js#L4583)).

Rather than a constant, this should depend on `LOG_BASE` as `mathpow(10, LOG_BASE)`

Also, `random` will produce a biased distribution if LOG_BASE is ever larger than 9 because of [this](https://github.com/MikeMcl/decimal.js/blob/3566299686993864f1a795954f189cdfbf8e4ff9/decimal.js#L4599) and [this](https://github.com/MikeMcl/decimal.js/blob/3566299686993864f1a795954f189cdfbf8e4ff9/decimal.js#L4577). Thus, we should throw an error if this ever happens (LOG_BASE > 9) rather than *silently* return a biased distribution.

**Comment by MikeMcl** [comment]
Yes, the library would break in several ways if `LOG_BASE` is not `7`. That is why is is not configurable by the user at runtime and it is not in the `EDITABLE DEFAULTS` section of the source code.

My original intention was to make `LOG_BASE` adjustable, but it would be quite a lot of work and it may bloat the code unnecessarily and make the library less efficient, so I no longer consider it important.

You are right that for consistency at least I should use `mathpow(10, LOG_BASE)` or `BASE` instead of the magic number `1e7` in the source code.

To make it clear for other readers, this is a minor code quality issue, the `random` method is not biased.
