### ISSUE TITLE
`crypto: true` setting doesn't work in latest versions of node.js (v8.2.1)

### ISSUE THREAD

**Issue by LJNeon** [MikeMcl/decimal.js#64]
Just thought I'd point this out, also v8 is becoming the LTS this October so full support for it is ideal.

My Code:
```
const crypto = require("crypto"), decimal = require("decimal.js");
decimal.set({rounding: decimal.ROUND_HALF_DOWN, minE: -2043, maxE: 2043, toExpNeg: -3, toExpPos: 3, crypto: true});
console.log(new decimal("999e2042").valueOf());
```
The Error:
```
/home/ubuntu/workspace/node_modules/decimal.js/decimal.js:4194
            throw Error(cryptoUnavailable);
            ^

Error: [DecimalError] crypto unavailable
    at Function.config (/home/ubuntu/workspace/node_modules/decimal.js/decimal.js:4194:19)
    at Object.<anonymous> (/home/ubuntu/workspace/test.js:2:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

**Comment by LJNeon** [comment]
Also looking at it this is the recommended method to check for crypto support on the official node.js docs.
[![Screenshot 1](https://user-images.githubusercontent.com/23249107/28992302-1257830e-794d-11e7-9cbb-80811269b0c7.png)](https://nodejs.org/api/crypto.html#crypto_determining_if_crypto_support_is_unavailable)
While this is how you actually implemented it:
[![Screenshot 2](https://user-images.githubusercontent.com/23249107/28992327-a32524e0-794d-11e7-99e1-10bc8913d621.png)](https://github.com/MikeMcl/decimal.js/blob/master/decimal.js#L4190-L4195)
(click both images for direct links)

**Comment by MikeMcl** [comment]
Yes, I [removed](https://github.com/MikeMcl/decimal.js/blob/master/CHANGELOG.md#700) the `require('crypto')` last year because it caused too many problems with using this library in the browser.

Unfortunately, `crypto` now needs to be added to the global object to use `crypto: true`when using the library with node.js.

`global.crypto = require('crypto')`

**Comment by LJNeon** [comment]
then maybe make two different builds of this lib, one for node and one for the browser?  This would make it a lot simpler right?

**Comment by MikeMcl** [comment]
No, it would make it more complicated.

It is simple to define a global `crypto` variable in both the browser and node.js. In node.js, it can be thought of as just like other native, built-in globals such as `process` and `console`, with the exception that `require` has to be used with `crypto` because it is possible to build node.js without it.

I just need to improve the documentation, which I will do shortly.
