### ISSUE TITLE
isDecimal check would report different results for clone instances depending on minification

### ISSUE THREAD

**Issue by cag** [MikeMcl/decimal.js#77]
```js
Decimal9 = Decimal.clone({ precision: 9, rounding: 1 })

y = new Decimal9(5)

Decimal.isDecimal(y) // true if not minified, but false if minified
```

**Comment by MikeMcl** [comment]
It works fine when I try it in the console with the minified version incorporated into the [documentation](http://mikemcl.github.io/decimal.js/).

If it does not work for you, it means that your minifier is mangling, i.e. renaming, the `name` property of the Decimal prototype object. I don't think it is anything to do with using `Decimal.clone`.

The minifier shouldn't be mangling *any* property names, otherwise the library cannot be expected to work as it should do.

If you post the minified code below I will have a look at it.

**Comment by MikeMcl** [comment]
"> isDecimal check would report different results for clone instances depending on minification"

No, it wouldn't.
