### ISSUE TITLE
[Feature] Implement `expm1`, `log1p` and `log2`

### ISSUE THREAD

**Issue by harrysarson** [MikeMcl/decimal.js#89]
ECMAScript 2015 added [`expm1`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/expm1), [`log1p`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log1p) ~~and [`log2`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/log2)~~.

The pull https://github.com/josdejong/mathjs/pull/1046 is attempting to add these functions into mathjs and I was wondering if decimal.js would be interested in including these three new functions.

 - ~~`log2(x) == ln(x)/ln(2)` which is easy to add.~~
 - I found numpy's implementation of `log1p` and `expm1` in https://github.com/numpy/numpy/blob/d407f24cb5ad85850a60b1be3dade3305ea30c98/numpy/core/src/npymath/npy_math_internal.h.src which does not look too complicated.

I guess decimal.js would want to rename `log1p` ro  `ln1p` for consistancy.

**Comment by MikeMcl** [comment]
This library already has `log2`.

One reason I didn't add `log1p` is because, as you recognise, the default base of `log` is 10 here, and if the name is not going to be the same there seemed little point adding it.

More importantly, my understanding is that `expm1` and its inverse function `log1p` are only really relevant to binary floating point, increasing the precision of the exponential and natural logarithm functions when the argument is near zero.

The `exp` and `ln` methods of this library are precise whatever the argument anyway.
