### ISSUE TITLE
Compile error when using with Jest

### ISSUE THREAD

**Issue by hudovisk** [MikeMcl/decimal.js#96]
Not sure what is happening, but I am getting the following error `SyntaxError: Unexpected token export` in the file `node_modules/decimal.js/decimal.mjs:4789` while running my tests with jest.

It seems that babel is not transpiling this file while running jest, this is my current jest configuration:
```json
"jest": {
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,mjs}"
    ],
    "setupFiles": [
      "<rootDir>/config/polyfills.js",
      "jest-localstorage-mock"
    ],
    "testMatch": [
      "<rootDir>/src/**/__tests__/**/*.{js,jsx,mjs}",
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest",
      "^.+\\.css$": "<rootDir>/config/jest/cssTransform.js",
      "^(?!.*\\.(js|jsx|mjs|css|json)$)": "<rootDir>/config/jest/fileTransform.js"
    },
    "moduleDirectories": [
      "node_modules",
      "src"
    ],
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "moduleNameMapper": {
      "^react-native$": "react-native-web"
    },
    "moduleFileExtensions": [
      "web.js",
      "mjs",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node"
    ]
  },
  "babel": {
    "presets": [
      "react-app"
    ]
  },
```
This is the default config from create-react-app and running eject. Already tried to change the `transformIgnorePatterns` to:
```json
"transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx)$"
    ],
```
But nothing changes. Doing some research I found this: https://github.com/facebook/jest/issues/4637

**Comment by MikeMcl** [comment]
From your link, it seems that *.mjs* files are not supported.
Perhaps you could use *decimal.js*.
I am not able to help with this.

**Comment by haraldrudell** [comment]
It appears you are importing an ECMAScript module from the node_modules directory

To do this, you must reconfigure the **transform** keyword to include the imported .mjs files

Transpiling dependencies in this way during testing will likely give you lots of troubles but will eventually work if customized to your current dependency tree using trial and error

You could also reconfigure your test build to import CommonJS versions of your dependencies, ie. using the main keyword instead of module from the dependency's package.json

As of jest 22.4.3 this is an inherit limitation since jest is pre-ECMAScript modules This will change once the Node.js --experimental-modules flag can be used

(I did not try my suggestion)

**Comment by MikeMcl** [comment]
I wonder if you still get this issue with the latest release: *v7.2.1*?
